version: '3'
services:

  db:
    image: yitakura731/simple-repository-db
    restart: always
    build:
      context: ./sr-db/
      dockerfile: Dockerfile
    container_name: sr-db
    env_file:
      - ./sr-db/db.env
    volumes:
      - '/sr-storage/db:/data/db'
    ports:
      - "27017:27017"


  rep:
    image: yitakura731/simple-repository-rep
    build:
      context: ./sr-repository/
      dockerfile: Dockerfile
    container_name: sr-rep
    env_file:
      - ./sr-repository/rep.env
    volumes:
      - "/sr-storage/files:/sr-storage/files"
      - "/SimpleRepository/sr-repository/cert:/src/cert"
    ports:
      - "3000:3000"
    depends_on: 
      - db


  web:
    image: yitakura731/simple-repository-web
    build:
      context: ./sr-view/
      dockerfile: Dockerfile
    container_name: sr-web
    env_file:
      - ./sr-view/app.env
    volumes:
      - "/SimpleRepository/sr-view/cert:/certs"
    ports:
      - "443:443"
    depends_on:
      - rep
