version: '3'
services:

  db:
    image: yitakura731/simple-repository-db
    restart: always
    build:
      context: ./sr-db/
      dockerfile: Dockerfile
    container_name: sr-db
    env_file:
      - ./sr-db/db.env
    volumes:
      - '${DB_DATA_PATH}:/data/db'
    ports:
      - "${DB_PORT}:${DB_PORT}"


  rep:
    image: yitakura731/simple-repository-rep
    build:
      context: ./sr-repository/
      dockerfile: Dockerfile
    container_name: sr-rep
    env_file:
      - ./sr-repository/rep.env
    volumes:
      - "${REPOSITORY_DATA_PATH}:${REPOSITORY_DATA_PATH}"
      - "${REPOSITORY_CERT_STORE}:/src/cert"
    ports:
      - "${REPOSITORY_PORT}:${REPOSITORY_PORT}"
    depends_on: 
      - db


  web:
    image: yitakura731/simple-repository-web
    build:
      context: ./sr-view/
      dockerfile: Dockerfile
      args: 
        APP_NAME: ${APP_NAME}
    container_name: sr-web
    env_file:
      - ./sr-view/app.env
    volumes:
      - "${WEB_SERVER_CERT_STORE}:/certs"
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    depends_on:
      - rep
